package GUI.admin;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import javax.swing.*;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import Classes.Compensation;
import Classes.EmployeeInformation;
import Classes.GovernmentIdentification;
import GUI.LoginPage;
import UtilityClasses.JsonFileHandler;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;


@SuppressWarnings("serial")
public class DashboardPage extends JFrame {

	private JLabel employeeId = new JLabel("Employee ID:");

	// Last Name
	private JLabel lastName = new JLabel("Last Name:");
	private JLabel lastNameValue = new JLabel("");

	// First Name
	private JLabel firstName = new JLabel("First Name:");
	private JLabel firstNameValue = new JLabel("");

	// Birthday
	private JLabel birthday = new JLabel("Birthday:");
	private JLabel birthdayValue = new JLabel("");

	// Address
	private JLabel address = new JLabel("Address:");
	private JLabel addressValue = new JLabel("");

	// Phone Number
	private JLabel phoneNumber = new JLabel("Phone Number:");
	private JLabel phoneNumberValue = new JLabel("");

	// SSS Number
	private JLabel sssNumber = new JLabel("SSS Number:");
	private JLabel sssNumberValue = new JLabel("");

	// PhilHealth Number
	private JLabel philhealthNumber = new JLabel("PhilHealth Number:");
	private JLabel philhealthNumberValue = new JLabel("");

	// TIN Number
	private JLabel tinNumber = new JLabel("TIN Number:");
	private JLabel tinNumberValue = new JLabel("");

	// Pag-IBIG Number
	private JLabel pagibigNumber = new JLabel("Pag-IBIG Number:");
	private JLabel pagibigNumberValue = new JLabel("");

	// Status
	private JLabel status = new JLabel("Status:");
	private JLabel statusValue = new JLabel("");

	// Position
	private JLabel position = new JLabel("Position:");
	private JLabel positionValue = new JLabel("");

	// Immediate Supervisor
	private JLabel immediateSupervisor = new JLabel("Immediate Supervisor:");
	private JLabel immediateSupervisorValue = new JLabel("");

	// Hourly Rate
	private JLabel hourlyRate = new JLabel("Hourly Rate:");
	private JLabel hourlyRateValue = new JLabel("");

	// Interactibles
	private JTextField employeeIdField = new JTextField(30);
	private JButton searchButton = new JButton("Search");
	private JButton computeButton = new JButton("Compute Salary");
	private JButton employeeListButton = new JButton("Employee List");
	private JButton leaveRequestButton = new JButton("Leave Requests");
	private JButton logoutButton = new JButton("Log Out");;
	private JLabel[] labels = { lastNameValue, firstNameValue, birthdayValue, addressValue, phoneNumberValue,
			sssNumberValue, philhealthNumberValue, tinNumberValue, pagibigNumberValue, statusValue, positionValue,
			immediateSupervisorValue, hourlyRateValue };
	private String[] stringifiedLabels = { "employeeNum", "last_name", "first_name", "birthday", "address",
			"phone_number", "SSS", "Philhealth", "TIN", "Pag-ibig", "Status", "Position", "immediate_supervisor",
			"hourly_rate" };

	// Instantiate two of the user's important information
	GovernmentIdentification employeeGI = new GovernmentIdentification(employeeIdField.getText());
	Compensation employeeComp = new Compensation(employeeIdField.getText());

	// Panels
	private javax.swing.JPanel dashboardPanel;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel addressPanel;

	/**
	 * Creates new form NewJFrame
	 */
	public DashboardPage() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// @SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		dashboardPanel = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		addressPanel = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);
		setTitle("MotorPH Payroll System | Dashboard");

		dashboardPanel.setBackground(new java.awt.Color(255, 255, 255));

		employeeId.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		employeeId.setText("Employee ID:");

		employeeIdField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		employeeIdField.setToolTipText("Please enter an ID");
		employeeIdField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				employeeIdFieldActionPerformed(evt);
			}
		});

		searchButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		searchButton.setText("Search");
		searchButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				searchButtonActionPerformed(evt);
			}
		});

		computeButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		computeButton.setText("Compute Salary");
		computeButton.setEnabled(false);
		computeButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				computeButtonActionPerformed(evt);
			}
		});

		employeeListButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		employeeListButton.setText("Employee List");
		employeeListButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				employeeListButtonActionPerformed(evt);
			}
		});

		leaveRequestButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		leaveRequestButton.setText("Leave Requests");
		leaveRequestButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					leaveRequestButtonActionPerformed(evt);
				} catch (FileNotFoundException e) {
					e.printStackTrace();
				}
			}
		});

		logoutButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		logoutButton.setText("Log Out");
		logoutButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				logoutButtonActionPerformed(evt);
			}
		});

		jPanel1.setBackground(new java.awt.Color(204, 204, 204));
		jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		firstName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		firstName.setText("First Name");

		firstNameValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		firstNameValue.setText(" ");

		lastName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		lastName.setText("Last Name");

		lastNameValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		lastNameValue.setText(" ");

		birthday.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		birthday.setText("Birthday");

		birthdayValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		birthdayValue.setText(" ");

		phoneNumber.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		phoneNumber.setText("Phone Number");

		phoneNumberValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		phoneNumberValue.setText(" ");

		javax.swing.GroupLayout gl_jPanel1 = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(gl_jPanel1);
		gl_jPanel1.setHorizontalGroup(gl_jPanel1.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(gl_jPanel1.createSequentialGroup().addGap(17, 17, 17).addGroup(gl_jPanel1
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(phoneNumber)
						.addComponent(birthday).addComponent(lastName).addComponent(firstName)
						.addComponent(firstNameValue, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
						.addComponent(lastNameValue, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(birthdayValue, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(phoneNumberValue, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap(44, Short.MAX_VALUE)));
		gl_jPanel1.setVerticalGroup(gl_jPanel1.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gl_jPanel1.createSequentialGroup()
						.addContainerGap(29, Short.MAX_VALUE).addComponent(firstName)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(firstNameValue)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(lastName)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(lastNameValue)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(birthday)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(birthdayValue)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(phoneNumber)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(phoneNumberValue).addGap(29, 29, 29)));

		jPanel2.setBackground(new java.awt.Color(204, 204, 204));
		jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		status.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		status.setText("Status");

		statusValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		statusValue.setText(" ");

		position.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		position.setText("Position");

		positionValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		positionValue.setText(" ");

		immediateSupervisor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		immediateSupervisor.setText("Immediate Supervisor");

		immediateSupervisorValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		immediateSupervisorValue.setText(" ");

		hourlyRate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		hourlyRate.setText("Hourly Rate");

		hourlyRateValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		hourlyRateValue.setText(" ");

		javax.swing.GroupLayout gl_jPanel2 = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(gl_jPanel2);
		gl_jPanel2.setHorizontalGroup(gl_jPanel2.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(gl_jPanel2.createSequentialGroup().addGap(30, 30, 30)
						.addGroup(gl_jPanel2.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(hourlyRate).addComponent(immediateSupervisor).addComponent(position)
								.addComponent(status)
								.addComponent(statusValue, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
								.addComponent(positionValue, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(immediateSupervisorValue, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(hourlyRateValue, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap(31, Short.MAX_VALUE)));
		gl_jPanel2.setVerticalGroup(gl_jPanel2.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(gl_jPanel2.createSequentialGroup().addGap(29, 29, 29).addComponent(status)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(statusValue)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(position)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(positionValue)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(immediateSupervisor)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(immediateSupervisorValue)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(hourlyRate)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(hourlyRateValue)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel3.setBackground(new java.awt.Color(204, 204, 204));
		jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		sssNumber.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		sssNumber.setText("SSS Number");

		sssNumberValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		sssNumberValue.setText(" ");

		philhealthNumber.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		philhealthNumber.setText("PhilHealth Number");

		philhealthNumberValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		philhealthNumberValue.setText(" ");

		pagibigNumber.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		pagibigNumber.setText("Pag-ibig Number");

		pagibigNumberValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		pagibigNumberValue.setText(" ");

		tinNumber.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		tinNumber.setText("TIN Number");

		tinNumberValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		tinNumberValue.setText(" ");

		javax.swing.GroupLayout gl_jPanel3 = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(gl_jPanel3);
		gl_jPanel3.setHorizontalGroup(gl_jPanel3.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(gl_jPanel3.createSequentialGroup().addGap(33, 33, 33).addGroup(gl_jPanel3
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(tinNumber)
						.addComponent(pagibigNumber).addComponent(philhealthNumber).addComponent(sssNumber)
						.addComponent(sssNumberValue, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
						.addComponent(philhealthNumberValue, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(pagibigNumberValue, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(tinNumberValue, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap(34, Short.MAX_VALUE)));
		gl_jPanel3.setVerticalGroup(gl_jPanel3.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(gl_jPanel3.createSequentialGroup().addGap(29, 29, 29).addComponent(sssNumber)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(sssNumberValue)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(philhealthNumber)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(philhealthNumberValue)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(pagibigNumber).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(pagibigNumberValue)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(tinNumber)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(tinNumberValue)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		addressPanel.setBackground(new java.awt.Color(204, 204, 204));
		addressPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

		address.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		address.setText("Address");

		addressValue.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		addressValue.setText(" ");

		javax.swing.GroupLayout gl_addressPanel = new javax.swing.GroupLayout(addressPanel);
		addressPanel.setLayout(gl_addressPanel);
		gl_addressPanel.setHorizontalGroup(gl_addressPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(gl_addressPanel.createSequentialGroup().addGap(15, 15, 15)
						.addGroup(gl_addressPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(address).addComponent(addressValue,
										javax.swing.GroupLayout.PREFERRED_SIZE, 785,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(16, Short.MAX_VALUE)));
		gl_addressPanel.setVerticalGroup(gl_addressPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(gl_addressPanel.createSequentialGroup().addGap(12, 12, 12).addComponent(address)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(addressValue)
						.addContainerGap(13, Short.MAX_VALUE)));

		javax.swing.GroupLayout gl_dashboardPanel = new javax.swing.GroupLayout(dashboardPanel);
		gl_dashboardPanel.setHorizontalGroup(
			gl_dashboardPanel.createParallelGroup(Alignment.TRAILING)
				.addGroup(gl_dashboardPanel.createSequentialGroup()
					.addContainerGap(59, Short.MAX_VALUE)
					.addGroup(gl_dashboardPanel.createParallelGroup(Alignment.LEADING)
						.addComponent(addressPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addGroup(gl_dashboardPanel.createSequentialGroup()
							.addGroup(gl_dashboardPanel.createParallelGroup(Alignment.TRAILING)
								.addComponent(computeButton, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
								.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addGroup(gl_dashboardPanel.createParallelGroup(Alignment.LEADING, false)
								.addGroup(gl_dashboardPanel.createSequentialGroup()
									.addComponent(leaveRequestButton, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(ComponentPlacement.RELATED)
									.addComponent(employeeListButton, GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
								.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
					.addGap(50))
				.addGroup(gl_dashboardPanel.createSequentialGroup()
					.addGap(137)
					.addComponent(employeeId)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(employeeIdField, GroupLayout.PREFERRED_SIZE, 257, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(searchButton, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
					.addComponent(logoutButton)
					.addContainerGap())
		);
		gl_dashboardPanel.setVerticalGroup(
			gl_dashboardPanel.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_dashboardPanel.createSequentialGroup()
					.addGap(18)
					.addGroup(gl_dashboardPanel.createParallelGroup(Alignment.BASELINE)
						.addComponent(employeeIdField, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
						.addComponent(searchButton, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
						.addComponent(employeeId)
						.addComponent(logoutButton, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(gl_dashboardPanel.createParallelGroup(Alignment.BASELINE)
						.addComponent(leaveRequestButton, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
						.addComponent(employeeListButton, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
						.addComponent(computeButton, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
					.addGap(20)
					.addGroup(gl_dashboardPanel.createParallelGroup(Alignment.LEADING)
						.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
						.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(addressPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addGap(55))
		);
		dashboardPanel.setLayout(gl_dashboardPanel);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();

		// Must be called after setting pack
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void employeeIdFieldActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			// Iterate through the JSON file for the employee data
			JsonObject employeeData = JsonFileHandler.nameIterator(JsonFileHandler.getEmployeesJSON(), "employeeNum",
					employeeIdField.getText());

			// Iterate through the data and set labels
			setLabelValues(employeeData);
		} catch (IOException e1) {
			// Handle IOException
			e1.printStackTrace();
		}
	}

	private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:

		try {

			// Iterate through the JSON file for the employee data
			JsonObject employeeData = JsonFileHandler.nameIterator(JsonFileHandler.getEmployeesJSON(), "employeeNum",
					employeeIdField.getText());

			// Iterate through the data and set labels
			setLabelValues(employeeData);
		} catch (IOException e1) {
			// Handle IOException
			e1.printStackTrace();
		}
	}

	private void computeButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		openCalculator(employeeComp);
	}

	private void employeeListButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				// Remove the DashboardPage Window
				dispose();

				// Go to the employees list page
				new EmployeeListPage().setVisible(true);
			}
		});
	}

	private void leaveRequestButtonActionPerformed(java.awt.event.ActionEvent evt) throws FileNotFoundException {
		// Read the JSON file and parse it using GSON
		FileReader reader = new FileReader(JsonFileHandler.getLeaveRequestJsonPath());
		JsonElement jsonElement = JsonParser.parseReader(reader);

		// Check if the parsed JSON is an array
		if (!jsonElement.isJsonArray()) {
			// Display a message to the user
			JOptionPane.showMessageDialog(this, "No leave requests found.", "Empty Data",
					JOptionPane.INFORMATION_MESSAGE);

			return;
		}

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				// Close the dashboard page
				dispose();

				// Log out
				try {
					new LeaveRequestListPage(employeeGI, employeeComp).setVisible(true);
				} catch (ParseException e) {
					e.printStackTrace();
				}
			}
		});
	}

	private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				// Close the dashboard page
				dispose();

				// Log out
				new LoginPage().setVisible(true);
			}
		});
	}

	public Boolean checkForEmployee(JsonObject employeeData) throws IOException {
		// Return if employeeIdField is empty
		if (employeeIdField.getText().equals("")) {
			JOptionPane.showMessageDialog(new JFrame(""), "Please provide an employee number.", "No input detected",
					JOptionPane.ERROR_MESSAGE);
			return false;
		}

		// Before iterating through the labels, check if employee data is null
		if (employeeData == null) {
			JOptionPane.showMessageDialog(new JFrame(""), "No user found.", "Error", JOptionPane.ERROR_MESSAGE);
			return false;
		}

		return true;
	}

	public void setLabelValues(JsonObject employeeData) throws IOException {
		// Check if user exists
		if (!checkForEmployee(employeeData)) {
			return;
		}

		// Reassign the values of the labels
		JsonFileHandler.labelAssigner(employeeData, stringifiedLabels, labels);

		// Set the employeeData to the employeeComp and employeeGI objects
		EmployeeInformation.setEmployeeInformationObject(employeeIdField.getText(), employeeGI, employeeComp);

		// Let user click the compute button if user exists
		computeButton.setEnabled(true);
	}

	public void openCalculator(Compensation employeeComp) {
		// Open the calculator
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CalculatorPage(employeeComp).setVisible(true);
			}
		});
	}

	public void setEmployeeInformationObject(JsonObject employeeData) {

		// Instantiate Gson to get their Json counterparts
		Gson gson = new Gson();
		GovernmentIdentification employeeGovInfo = gson.fromJson(employeeData, GovernmentIdentification.class);
		Compensation employeeCompInfo = gson.fromJson(employeeData, Compensation.class);

		// Set Government Identification data of Employee
		employeeGI.setSSSNumber(employeeGovInfo.getSSSNumber());
		employeeGI.setPhilHealthNumber(employeeGovInfo.getPhilHealthNumber());
		employeeGI.setPagibigNumber(employeeGovInfo.getPagibigNumber());
		employeeGI.setTinNumber(employeeGovInfo.getTinNumber());

		// Set Compensation data of Employee
		employeeComp.setBasicSalary(employeeCompInfo.getBasicSalary());
		employeeComp.setClothingAllowance(employeeCompInfo.getClothingAllowance());
		employeeComp.setGrossSemiMonthlyRate(employeeCompInfo.getGrossSemiMonthlyRate());
		employeeComp.setPhoneAllowance(employeeCompInfo.getPhoneAllowance());
		employeeComp.setRiceSubsidy(employeeCompInfo.getRiceSubsidy());
		employeeComp.setHourlyRate(employeeCompInfo.getHourlyRate());
	}

}
